version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
